---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"
    state: fixed

- name: install node
  shell: curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - && sudo apt-get install -y nodejs

- name: "install npm."
  become: true
  apt:
    name: ["npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    version: 4.5.6
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: ./backend-app
    state: directory