---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"
    state: fixed
#- name: install nvm
#  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh 

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

#- name: Install node and set version
#  become: true
#  become_user: root
#  shell: "source /root/.nvm/nvm.sh && nvm install 12.0.0" 
#  args:
#    executable: /bin/bash

- name: install aws cli
  become: true
  become_user: root
  shell: pip3 install awscli  

#- name: "install npm."
#  become: true
#  apt:
#    name: ["npm"]
#    state: latest
#    update_cache: yes

- name: "Persist environment variables."
  shell:
    cmd: |
      ENVIRONMENT=/home/ubuntu/.profile
      echo "export NODE_ENV=production" >> $ENVIRONMENT
      echo "export VERSION=1" >> $ENVIRONMENT
      echo "export TYPEORM_CONNECTION=$TYPEORM_CONNECTION" >> $ENVIRONMENT
      echo "export TYPEORM_ENTITIES=$TYPEORM_ENTITIES" >> $ENVIRONMENT
      echo "export TYPEORM_HOST=$TYPEORM_HOST" >> $ENVIRONMENT
      echo "export TYPEORM_PORT=$TYPEORM_PORT" >> $ENVIRONMENT
      echo "export TYPEORM_USERNAME=$TYPEORM_USERNAME" >> $ENVIRONMENT
      echo "export TYPEORM_PASSWORD=$TYPEORM_PASSWORD" >> $ENVIRONMENT
      echo "export TYPEORM_DATABASE=$TYPEORM_DATABASE" >> $ENVIRONMENT
      echo "export TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS" >> $ENVIRONMENT
      echo "export TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR" >> $ENVIRONMENT

- name: "install pm2"
  become: true
  npm:
    name: pm2
    version: 4.5.6
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: ./backend-app
    state: directory