---
#- name: "wait 600 sec"
#  wait_for_connection:

- name: "copy backend folder"
  become: true
  copy:
    src: ~/udacitycicd/backend
    dest: /home/ubuntu

- name: Install Node Dependencies
  shell: |
    cd /home/ubuntu/backend
    npm install

- name: Building backend service
  shell: |
    cd /home/ubuntu/backend
    npm run build
      
- name: Running backend service
  shell: |
    cd /home/ubuntu/backend    
    . ~/.profile
    pm2 start npm --no-automation --name "backend" -- run start
    echo Backend started.