---
- name: "copy backend folder"
  become: true
  copy:
    src: ~/udacitycicd/backend
    dest: /home/ubuntu

- name: Running backend service
  shell: |
    cd /home/ubuntu/backend    
    pm2 start npm --no-automation --name "backend" -- run start